import { createHash } from "node:crypto";
import { JSDOM } from "jsdom";
import type { Reading } from "../../../web/src/contract/common.ts";
import type { Job } from "../scheduler.ts";
import { keep, kept, note, ok, setState, state, waiting } from "../store.ts";
import { askFor } from "./ask.ts";
import { abs, base, get, normalPath, siteHost } from "./http.ts";
import { issue, type Issue } from "./rules.ts";

/**
 * The sitemap and robots.txt, read every quarter of an hour.
 *
 * The sitemap is the site's own statement of which pages it offers to search
 * engines, rebuilt on every deployment. So it is the desk's list of what to
 * crawl, and a change in it is news: an article was listed, a page was
 * written, an address was renamed.
 *
 * "CHANGED", NOT "REGENERATED". The file is regenerated by every build
 * whether or not anything in it differs. What is worth a line in the feed is
 * the set of addresses changing, and the line says which: "Sitemap changed:
 * 1 address added: /insights/…".
 *
 * Both files are validated the way a crawler depends on them: the sitemap is
 * well-formed XML, every address is on the canonical host, robots.txt allows
 * what the sitemap lists and names the sitemap. Each failure is an issue the
 * crawl folds into the site's score.
 */

export interface SitemapEntry {
  /** The stored address ("/seo", "/" for home). */
  path: string;
  /** The address exactly as the sitemap writes it. */
  loc: string;
  /** The sitemap's lastmod, as written, or null. The site gives one only to articles: the one date that is real. */
  lastmod: string | null;
  /** The sitemap's priority (0 to 1), or null. The site's own ranking of its pages against each other. */
  priority: number | null;
  changefreq: string | null;
}

export interface SitemapRead {
  /** When it was read, ISO. */
  at: string;
  /** The sitemap's HTTP status; 0 when nothing answered. */
  status: number;
  /**
   * The addresses. After a read that failed (no 200, or a 200 with no usable
   * address in it) these are the ones of the last read that worked, and
   * `entriesAt` says when that was.
   */
  entries: SitemapEntry[];
  /** When `entries` were read, when that is earlier than `at` because the latest read failed. Absent otherwise. */
  entriesAt?: string;
  robots: {
    status: number;
    /** Every "Sitemap:" line. */
    sitemaps: string[];
    /** How many allow and disallow rules apply to every crawler ("User-agent: *"). */
    rules: number;
  };
  /** What is wrong with either file. Empty means both are valid as far as the desk checks. */
  issues: Issue[];
}

/* ---------- robots.txt ------------------------------------------------------ */

export interface Robots {
  /** Rules by user agent, lower-cased; "*" is everyone. */
  groups: Map<string, { allow: boolean; pattern: string }[]>;
  sitemaps: string[];
}

/** Read a robots.txt. Unknown lines are skipped, as a crawler skips them. */
export function parseRobots(text: string): Robots {
  const groups = new Map<string, { allow: boolean; pattern: string }[]>();
  const sitemaps: string[] = [];
  let agents: string[] = [];
  let lastWasAgent = false;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.replace(/#.*$/, "").trim();
    const m = /^([A-Za-z-]+)\s*:\s*(.*)$/.exec(line);
    if (!m) continue;
    const field = (m[1] as string).toLowerCase();
    const value = (m[2] as string).trim();
    if (field === "user-agent") {
      /* Consecutive User-agent lines share one group; one after a rule starts a new group. */
      if (!lastWasAgent) agents = [];
      agents.push(value.toLowerCase());
      if (!groups.has(value.toLowerCase())) groups.set(value.toLowerCase(), []);
      lastWasAgent = true;
      continue;
    }
    lastWasAgent = false;
    if (field === "sitemap") sitemaps.push(value);
    else if ((field === "allow" || field === "disallow") && value) {
      for (const a of agents) groups.get(a)?.push({ allow: field === "allow", pattern: value });
    }
  }
  return { groups, sitemaps };
}

/** A robots pattern as a regular expression: "*" is anything, a final "$" is the end, the rest is literal. */
const patternRe = (pattern: string): RegExp =>
  new RegExp(
    `^${pattern
      .replace(/[.+?^{}()|[\]\\]/g, "\\$&")
      .replace(/\*/g, ".*")
      .replace(/\\?\$$/, "$")}`,
  );

/**
 * May a crawler fetch this path? The rule Google and RFC 9309 apply: the
 * longest matching pattern decides, and Allow wins a tie. No rule at all
 * means yes.
 */
export function allowed(robots: Robots, path: string, agent = "*"): boolean {
  const rules = robots.groups.get(agent.toLowerCase()) ?? robots.groups.get("*") ?? [];
  let best: { allow: boolean; pattern: string } | null = null;
  for (const r of rules) {
    if (!patternRe(r.pattern).test(path)) continue;
    if (!best || r.pattern.length > best.pattern.length || (r.pattern.length === best.pattern.length && r.allow)) best = r;
  }
  return best ? best.allow : true;
}

/* ---------- sitemap.xml ------------------------------------------------------ */

/**
 * Read a sitemap's XML. Returns the addresses and what is wrong with them.
 * `children` is filled instead when the file is an index of sitemaps.
 */
export function parseSitemap(xml: string): { entries: SitemapEntry[]; children: string[]; issues: Issue[] } {
  const entries: SitemapEntry[] = [];
  const children: string[] = [];
  const issues: Issue[] = [];
  let dom: JSDOM;
  try {
    dom = new JSDOM(xml, { contentType: "text/xml" });
  } catch (e) {
    issues.push(issue("sitemap.malformed", null, `sitemap.xml is not well-formed XML (${(e instanceof Error ? e.message : String(e)).split("\n")[0]?.slice(0, 120)}); crawlers discard a sitemap they cannot parse.`, "not well-formed", "well-formed XML"));
    return { entries, children, issues };
  }
  try {
    const doc = dom.window.document;
    const rootName = doc.documentElement?.localName;
    if (rootName === "sitemapindex") {
      for (const s of doc.getElementsByTagName("sitemap")) {
        const loc = s.getElementsByTagName("loc")[0]?.textContent?.trim();
        if (loc) children.push(loc);
      }
      return { entries, children, issues };
    }
    if (rootName !== "urlset") {
      issues.push(issue("sitemap.malformed", null, `sitemap.xml has the root element <${rootName ?? "none"}>; a sitemap's root is <urlset>.`, rootName ?? "none", "urlset"));
      return { entries, children, issues };
    }

    const seen = new Set<string>();
    const text = (el: Element, tag: string): string | null => el.getElementsByTagName(tag)[0]?.textContent?.trim() || null;
    for (const u of doc.getElementsByTagName("url")) {
      const loc = text(u, "loc");
      if (!loc) {
        issues.push(issue("sitemap.malformed", null, "sitemap.xml has a <url> with no <loc>.", "no <loc>", "<loc> in every <url>", undefined, "no-loc"));
        continue;
      }
      let url: URL | null = null;
      try {
        url = new URL(loc);
      } catch {
        /* handled below */
      }
      if (!url || `${url.protocol}//${url.host}` !== base()) {
        issues.push(issue("sitemap.off-host", null, `The sitemap lists ${loc}, which is not on ${base()}; a sitemap may only list its own host.`, loc, base(), undefined, loc));
        continue;
      }
      const path = normalPath(url.pathname);
      if (seen.has(path)) {
        issues.push(issue("sitemap.duplicate", null, `The sitemap lists ${path} twice; once is enough.`, 2, 1, undefined, path));
        continue;
      }
      seen.add(path);
      const priority = text(u, "priority");
      entries.push({
        path,
        loc,
        lastmod: text(u, "lastmod"),
        priority: priority !== null && Number.isFinite(Number(priority)) ? Number(priority) : null,
        changefreq: text(u, "changefreq"),
      });
    }
    if (!entries.length && !issues.length) {
      issues.push(issue("sitemap.malformed", null, "sitemap.xml lists no address at all.", 0, "at least 1"));
    }
    return { entries, children, issues };
  } finally {
    dom.window.close();
  }
}

/* ---------- the job ----------------------------------------------------------- */

const KEY = "site:sitemap";

/** Fetch and validate both files. Nothing is stored. Exported so the check script can time it alone. */
export async function readSitemap(): Promise<SitemapRead> {
  const at = new Date().toISOString();
  const issues: Issue[] = [];
  const sitemapUrl = abs("/sitemap.xml");

  const got = await get(sitemapUrl, { accept: "application/xml,text/xml,*/*;q=0.5" });
  let entries: SitemapEntry[] = [];
  if (got.status !== 200 || !got.body) {
    issues.push(issue("sitemap.unreachable", null, got.status === 0 ? `sitemap.xml did not answer (${got.error ?? "no reply"}); it should answer 200.` : `sitemap.xml answers ${got.status}; it should answer 200.`, got.status, 200));
  } else {
    const parsed = parseSitemap(got.body);
    issues.push(...parsed.issues);
    entries = parsed.entries;
    /* An index of sitemaps: read each child, one after the other. The site has
       a single file today; this is here so the day it splits is not a blank. */
    for (const child of parsed.children.slice(0, 10)) {
      const c = await get(child, { accept: "application/xml,text/xml,*/*;q=0.5" });
      if (c.status !== 200 || !c.body) {
        issues.push(issue("sitemap.unreachable", null, `${child}, named by the sitemap index, answers ${c.status || "nothing"}; it should answer 200.`, c.status, 200, undefined, child));
        continue;
      }
      const sub = parseSitemap(c.body);
      issues.push(...sub.issues);
      const have = new Set(entries.map((e) => e.path));
      entries.push(...sub.entries.filter((e) => !have.has(e.path)));
    }
  }

  const robotsGot = await get(abs("/robots.txt"), { accept: "text/plain,*/*;q=0.5" });
  let robots: Robots = { groups: new Map(), sitemaps: [] };
  if (robotsGot.status !== 200 || robotsGot.body === null) {
    issues.push(issue("robots.unreachable", null, robotsGot.status === 0 ? `robots.txt did not answer (${robotsGot.error ?? "no reply"}).` : `robots.txt answers ${robotsGot.status}; it should answer 200.`, robotsGot.status, 200));
  } else {
    robots = parseRobots(robotsGot.body);
    if (!robots.sitemaps.some((s) => s.replace(/\/+$/, "") === sitemapUrl)) {
      issues.push(
        issue(
          "robots.no-sitemap",
          null,
          robots.sitemaps.length ? `robots.txt names ${robots.sitemaps.join(", ")} as its sitemap, not ${sitemapUrl}.` : `robots.txt has no "Sitemap:" line; it should name ${sitemapUrl}.`,
          robots.sitemaps.length ? robots.sitemaps.join(", ") : "none",
          sitemapUrl,
        ),
      );
    }
    const blocked = entries.filter((e) => !allowed(robots, e.path) || !allowed(robots, e.path, "googlebot"));
    if (blocked.length) {
      issues.push(
        issue(
          "sitemap.blocked",
          null,
          `robots.txt forbids ${blocked.length} address${blocked.length === 1 ? "" : "es"} the sitemap lists (${blocked.slice(0, 3).map((b) => b.path).join(", ")}${blocked.length > 3 ? "…" : ""}); a page cannot be offered and forbidden at once.`,
          blocked.length,
          0,
          blocked.map((b) => b.path),
        ),
      );
    }
  }

  return {
    at,
    status: got.status,
    entries,
    robots: { status: robotsGot.status, sitemaps: robots.sitemaps, rules: (robots.groups.get("*") ?? []).length },
    issues,
  };
}

/** A short fingerprint of a set of addresses: equal sets, equal prints, whatever the order. The crawl stores the one it read. */
export const fingerprint = (paths: string[]): string => createHash("sha1").update([...paths].sort().join("\n")).digest("hex").slice(0, 16);

/** "/a, /b and 3 more" */
const some = (paths: string[]): string => `${paths.slice(0, 3).join(", ")}${paths.length > 3 ? ` and ${paths.length - 3} more` : ""}`;

/**
 * Read both files, keep the result, and when the set of addresses differs
 * from the last read say what changed and ask the crawl to run.
 *
 * A READ THAT GIVES NO ADDRESS IS A FAILED READ, whatever its status: one
 * that did not answer 200, and one that answered 200 with nothing usable in
 * it (an empty urlset, XML that does not parse, a wrong root, or every
 * address on another host, which is also what a wrong SITE_BASE looks like).
 * The previous addresses are kept, with this read's status and issues beside
 * them so the fault is visible; nothing is announced, no crawl is asked for,
 * and the job fails with the reason. One bad deploy or one bad minute must
 * not look like the whole site was unlisted: the crawl would call every page
 * gone, and call them all new again the day after.
 *
 * A read with SOME usable addresses is used as it is, its faults listed: an
 * odd address on another host does not stop the rest being the site's own
 * statement of what it offers.
 */
export async function refreshSitemap(): Promise<{ read: SitemapRead; added: string[]; removed: string[] }> {
  const read = await readSitemap();
  const had = kept<SitemapRead>(KEY)?.value ?? null;

  if (read.status !== 200 || !read.entries.length) {
    const why = read.status !== 200 ? (read.issues[0]?.text ?? "sitemap.xml did not answer") : (read.issues.find((i) => i.severity === "critical")?.text ?? "sitemap.xml lists no address at all.");
    if (had?.entries.length) {
      keep(KEY, { ...had, at: read.at, status: read.status, issues: read.issues, robots: read.robots, entriesAt: had.entriesAt ?? had.at });
      throw new Error(`${why} The ${had.entries.length} addresses of the last good read are kept.`);
    }
    keep(KEY, read);
    throw new Error(why);
  }
  keep(KEY, read);

  const now = read.entries.map((e) => e.path);
  const before = had?.entries.map((e) => e.path) ?? null;
  const mark = fingerprint(now);
  const added = before ? now.filter((p) => !before.includes(p)) : [];
  const removed = before ? before.filter((p) => !now.includes(p)) : [];

  if (before && (added.length || removed.length)) {
    const parts = [
      added.length ? `${added.length} address${added.length === 1 ? "" : "es"} added: ${some(added)}` : "",
      removed.length ? `${removed.length} removed: ${some(removed)}` : "",
    ].filter(Boolean);
    note("sitemap", `Sitemap changed: ${parts.join("; ")}`, {
      tone: "info",
      detail: `${now.length} addresses now, ${before.length} before`,
      href: abs("/sitemap.xml"),
      dedupe: `sitemap:${mark}`,
    });
  }
  setState("site:sitemap:set", mark);
  /* The crawl follows the sitemap: until a crawl has finished on THIS set of
     addresses, ask for one. Compared with what the crawl last read (it stores
     the print when it finishes), not with what this job last saw, so a crawl
     that was asked for and then lost to a restart is asked for again. */
  if (state("site:crawl:sitemap") !== mark) askFor("crawl", mark);
  return { read, added, removed };
}

/** The last read of the sitemap and robots.txt, as kept. Null before the first. */
export const lastSitemap = (): SitemapRead | null => kept<SitemapRead>(KEY)?.value ?? null;

/** The sitemap as a figure for a screen: its addresses, when it was read, and what is wrong with it. */
export function sitemap(): Reading<SitemapRead> {
  const had = kept<SitemapRead>(KEY);
  if (!had) return waiting("crawl", "The sitemap has not been read yet; the first read happens within a minute of the desk starting.");
  const v = had.value;
  const older = v.entriesAt ? ` The last read failed (see issues); the addresses are those read at ${v.entriesAt}.` : "";
  return ok(v, "crawl", had.at, `Read from ${siteHost()}/sitemap.xml and /robots.txt.${older}`);
}

/**
 * A new page in the sitemap is read and handed to Google at once, not the
 * next day (Fini, 8 October 2026: "they need to be crawled instantly when
 * they get published").
 *
 *   - the desk's own crawl runs now, so the new page's title, words and
 *     checks are on the SEO screens within minutes;
 *   - the sitemap is submitted to Google again, which is the one thing that
 *     makes Google fetch it sooner (there is no API to request indexing of an
 *     ordinary page). Bing and the IndexNow engines are told by the website's
 *     own deploy (its search workflow), so the desk does not tell them twice.
 *
 * Imported when needed: the scheduler and the Google actions import this
 * folder, and a top-level import back would be a cycle. A refusal from
 * Google (no write access yet) is said in the job's line and costs nothing.
 */
async function whenAdded(): Promise<string> {
  const said: string[] = [];
  const { runNow } = await import("../scheduler.ts");
  if (runNow("crawl")) said.push("crawl asked for");
  try {
    const google = await import("../seo/google-actions.ts");
    const desk = { telegram: 0, name: "The desk", email: null, author: "balkaris", canPublish: false, owner: false, revoked: false, seesLeads: false, grants: null, invitedAt: null } as unknown as import("../../people.ts").Person;
    await google.submitSitemap("/sitemap.xml", desk);
    said.push("sitemap submitted to Google");
  } catch (e) {
    said.push(`Google not told: ${e instanceof Error ? e.message : String(e)}`.slice(0, 160));
  }
  return `; ${said.join("; ")}`;
}

export const sitemapJob: Job = {
  name: "sitemap",
  title: "Read the sitemap and robots.txt",
  every: 15 * 60,
  delay: 45,
  run: async () => {
    const { read, added, removed } = await refreshSitemap();
    const change = added.length || removed.length ? `, ${added.length} added, ${removed.length} removed` : "";
    const faults = read.issues.length ? `, ${read.issues.length} problem${read.issues.length === 1 ? "" : "s"}` : ", valid";
    const after = added.length ? await whenAdded() : "";
    return `${read.entries.length} addresses${change}${faults}${after}`;
  },
};
